### ISSUE TITLE
Tarefa | Historia 1, 2 e 3 - Fazer um Login

### ISSUE THREAD

**Issue by HenriqueEstanislau** [ErickViniciusX/IT-BRAZIL-ACADEMY-SALTO-CC-GRUPO-05#9]
Precisamos fazer um login para a autenticação do usuário. 

O login deve conter:
- Campos: Email e Senha.
- Botão: Entrar

TDD:
- [ ] Tratar o campo do email para aceitar apenas emails válidos;
- [ ] A senha não deve aparecer quando o usuáro digitar, substituir os caracteres por " * ";
- [ ] A senha deve ser criptofada para ter mais segurança (sistema de Hash, usar MD5);
- [ ] Verificar se o usuário está cadastrado no banco de dados (Montar as tabelas);
- [ ] Se o usuário não estiver cadastrado mostrar uma mensagem na tela pedindo para entrar em contato com o administrador para que ele crie uma conta para o funcionário.
- [ ] Tratar SQL Injection.

**Comment by lucasbaquinoo** [comment]
Encerrando a issue por mudança de stack do projeto
